"""rename address

Revision ID: 1732cf218879
Revises: b482cd790e56
Create Date: 2025-06-14 21:14:20.927303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1732cf218879'
down_revision = 'b482cd790e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location', new_column_name = 'address' )
    # ### end Alembic commands ###
